### ISSUE TITLE
It only happens after resizing the window

### ISSUE THREAD

**Issue by Utz1** [tenbullstech/jquery-make-me-center#1]
Hi guys, first of all: Thank You for this nice plugin.

But i ran in to a problem with my little app, where i tried to install your plugin: It happens only after i change the size of my window. After that it works perfekt.
If i don't change the window size manually, the div to be centered, appears about at the right bottom of my page. Any idea, what i might be doing wrong?
I already tried to position your makemecenter.js on different places behind the jquery.js. But i received always the same effekt.

**Comment by tenbulls007** [comment]
Hi
Can you send me the link of page where you getting that issue so we can check and resolve it.

**Comment by Utz1** [comment]
Hi,
i feel very sorry for my issue – it turned out to be my fault: I had a missing semicolon somewhere in my javascript. It seems to me like that caused the issue. Now everything is working fine.
Thank You again for your work.
